name: Compress images
on:
  pull_request:
    paths:
      - 'docs/**.jpg'
      - 'docs/**.png'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: calibreapp/image-actions@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: "80"
          pngQuality: "90"
          ignorePaths: "node_modules/**,libs/**,docfiles/**,built/**"